#! /bin/sh
xrandr --output DVI-D-0 --off --output HDMI-0 --mode 1920x1080 --pos 1366x0 --rotate normal --output DP-0 --mode 1366x768 --pos 0x0 --rotate normal --output DP-1 --off &

bspc monitor -d I II III IV V VI VII VIII IX X

sxhkd &

sh ~/.config/polybar/launch_polybar.sh
#polybar example &

redshift &

feh --bg-scale ~/Pictures/mountain_aesthetic.png &

#"#"
bspc config normal_border_color "#484848"
bspc config focused_border_color "#8BE9FD"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config click_to_focus true
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr &

