#! /bin/sh

~/.screenlayout/main_res.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale /home/daniel/Pictures/default.jpg &
redshift -P -l 15:-48 -t 5000:3700 -b 1.0:1.0 &
bash /home/daniel/.config/lemonbar/lemonbar-bar.sh | lemonbar -p -b &

bspc monitor -d one two three four five

bspc config border_width         1
bspc config active_border_color  \#FF00FF
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

exec bspwm
