#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale /home/daniel/Pictures/default.jpg &
redshift -P -l 15:-48 -t 4500:3700 -b 0.8:0.7 &
bash /home/daniel/.config/lemonbar/lemonbar-bar.sh | lemonbar -p &

bspc monitor -d one two three four five

bspc config border_width         1
bspc config active_border_color  \#FF00FF
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

exec bspwm
