#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# unload the old theme
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi

# load the down script to the expected location
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# set background using .fehbg file if it exists
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $HOME/Pictures/wallpapers/spaceship_01.jpg
fi

eww daemon
eww open bar
